### ISSUE TITLE
Errore sulla local variable 'root'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fondazionebordoni/nemesys#6]
```
What steps will reproduce the problem?
1. Installazione secondo le istruzioni su Fedora 14
2. Esecuzione del demone

What is the expected output? What do you see instead?

$ sudo /etc/init.d/nemesys start
Starting Nemesys daemon... 

Traceback (most recent call last):
  File "<string>", line 254, in <module>
  File "<string>", line 210, in getCode
UnboundLocalError: local variable 'root' referenced before assignment

$

What version of the product are you using? On what operating system?
Nemesys_fastweb_1.6.5.11_2_Fedora14.rpm
Fedora 14

```

Original issue reported on code.google.com by `merli.st...@gmail.com` on 5 Jul 2011 at 8:37

**Comment by ewedlund** [comment]
Chiudo essendo molto vecchio e non ho visto segnalazioni simili.
